services:
  app:
    image: shogi-sensei
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: shogi-sensei

    stdin_open: true
    tty: true

    volumes:
      - ./src:/app/src