"""create exercise table

Revision ID: 21e2d49bac6c
Revises: e22f4444652c
Create Date: 2026-08-03 20:16:14.615617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e2d49bac6c'
down_revision: Union[str, Sequence[str], None] = 'e22f4444652c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sfen', sa.String(), nullable=False),
    sa.Column('hands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pieces_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    # ### end Alembic commands ###
