"""raw_games_processed_column

Revision ID: 8aa986ed6e82
Revises: 21e2d49bac6c
Create Date: 2026-08-03 21:06:00.518173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa986ed6e82'
down_revision: Union[str, Sequence[str], None] = '21e2d49bac6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_games', sa.Column('processed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_games', 'processed')
    # ### end Alembic commands ###
