"""create_user_status_table

Revision ID: c85fb3388442
Revises: a6fc23522501
Create Date: 2026-08-27 16:04:28.789956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c85fb3388442'
down_revision: Union[str, Sequence[str], None] = 'a6fc23522501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_module', sa.String(length=50), nullable=False),
    sa.Column('module_progress', sa.Float(), nullable=False),
    sa.Column('modules_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_performances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_status')
    # ### end Alembic commands ###
