"""initial schema

Revision ID: e22f4444652c
Revises: 
Create Date: 2026-05-21 23:36:54.614618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e22f4444652c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_games',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_comment', sa.String(), nullable=True),
    sa.Column('endgame', sa.String(), nullable=False),
    sa.Column('sfen', sa.String(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moves_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('var_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_games')
    # ### end Alembic commands ###
